### ISSUE TITLE
Link to uncharted_phoenix github 404s on Demo page

### ISSUE THREAD

**Issue by jsegal205** [unchartedelixir/demo#18]
Hello! I was looking through the demo site and the Github link to `Uncharted Phoenix` lands on a 404 page. 

I'm unsure if this is a private repo or just a mistype in the url as I couldn't find it in the list of repos for [UnchartedElixir](https://github.com/unchartedelixir)

<img width="400" alt="Uncharted Repos" src="https://user-images.githubusercontent.com/1733595/125634114-7ec2ae85-04b7-4c7e-80c9-798612c9c833.png">

## Repo steps: 

- Go to [https://unchartedelixir.herokuapp.com/](https://unchartedelixir.herokuapp.com/)
- Click the `Github` under the Uncharted Phoenix Header

<img width="491" alt="Uncharted Phoenix Link" src="https://user-images.githubusercontent.com/1733595/125633624-4de3ede3-aeee-4fbe-b789-77cb434c1620.png">

Link to update is found: https://github.com/unchartedelixir/demo/blob/master/lib/demo_web/live/page_live.html.leex#L10

**Comment by rheubach** [comment]
Thank you, @jsegal205 for bringing up this issue! We have updated the link to where we moved uncharted_phoenix into the uncharted repo.
